name: bamobile1
description: A new Flutter project.
publish_to: 'none'
version: 1.1.5+8

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter_bloc: ^8.1.5
  flutter_custom_clippers: ^2.1.0
  flutter:
    sdk: flutter
  card_swiper: ^3.0.1
  font_awesome_flutter: ^10.7.0
  json_annotation: ^4.9.0
  table_calendar: ^3.0.9
  syncfusion_flutter_datepicker: ^25.1.38
  intl: ^0.18.1
  bottom_picker: ^2.6.0
  country_list_pick: ^1.0.1+6
  country_code_picker: ^3.0.0
  flutter_localization: ^0.2.0
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  animated_splash_screen: ^1.3.0
  flutter_screenutil: ^5.9.3
  riverpod: ^2.5.1
  dio: ^5.4.3+1
  modal_progress_hud_nsn: ^0.5.1
  webview_flutter: ^4.8.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  timezone: ^0.9.4
  flutter_image_slideshow: ^0.1.6
  newsfeed_multiple_imageview: ^1.0.1
  url_launcher: ^6.3.1
  cloud_firestore: ^5.4.0
  cached_network_image: ^3.4.0
  firebase_core: ^3.4.0
  image_picker: ^1.1.2
  uuid: ^4.5.1
  firebase_storage: ^12.2.0
  flutter_picker: ^2.1.0
  slide_countdown: ^2.0.1
  pdf: ^3.11.1
  printing: ^5.12.0
  pdfx: ^2.6.0
  http: ^1.2.2
  otp: ^3.1.4
  flutter_otp_text_field: ^1.2.0
  html: ^0.15.5
  rename: ^3.0.2





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_logo.png" 


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: RobotoAmiri
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal-Bold.ttf
        - asset: fonts/Tajawal-Regular.ttf
    - family: Amiri
      fonts:
        - asset: fonts/Amiri-Regular.ttf
        - asset: fonts/Amiri-Bold.ttf        

   
flutter_intl:
  enabled: true
