// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnhz30ISbWxphNViSbywruzIppXETNTg4',
    appId: '1:723786357355:web:248c2b670037f452d9af2e',
    messagingSenderId: '723786357355',
    projectId: 'safari-a51b6',
    authDomain: 'safari-a51b6.firebaseapp.com',
    storageBucket: 'safari-a51b6.firebasestorage.app',
    measurementId: 'G-EDNFLRWH4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVbH1bw5xP1IpcLPCf7G1X_ubNnaBlClI',
    appId: '1:723786357355:android:002417c00e795201d9af2e',
    messagingSenderId: '723786357355',
    projectId: 'safari-a51b6',
    storageBucket: 'safari-a51b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQngbc45rqdcTboqNosfOxYq7Vcd757sM',
    appId: '1:723786357355:ios:914c5704b4e757c8d9af2e',
    messagingSenderId: '723786357355',
    projectId: 'safari-a51b6',
    storageBucket: 'safari-a51b6.firebasestorage.app',
    iosBundleId: 'com.kplus.safari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQngbc45rqdcTboqNosfOxYq7Vcd757sM',
    appId: '1:723786357355:ios:1afdcdfe129a33c5d9af2e',
    messagingSenderId: '723786357355',
    projectId: 'safari-a51b6',
    storageBucket: 'safari-a51b6.firebasestorage.app',
    iosBundleId: 'com.example.bamobile1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnhz30ISbWxphNViSbywruzIppXETNTg4',
    appId: '1:723786357355:web:d9373ef227bccaa3d9af2e',
    messagingSenderId: '723786357355',
    projectId: 'safari-a51b6',
    authDomain: 'safari-a51b6.firebaseapp.com',
    storageBucket: 'safari-a51b6.firebasestorage.app',
    measurementId: 'G-JK563JVQHN',
  );

}